#controllers:
#resource: ../src/Controller/
#type: attribute

# authentication
reset-password:
    path: /admin23111978/reset-password
    controller: App\Controller\Admin\ResetPasswordController::request

reset-password-check-email:
    path: /admin23111978/check-email
    controller: App\Controller\Admin\ResetPasswordController::checkEmail

reset-password-uno:
    path: /admin23111978/reset-password/{$slug}
    controller: App\Controller\Admin\ResetPasswordController::request

login:
    path: /admin23111978/login
    controller: App\Controller\Admin\SecurityController::login

logout:
    path: /admin23111978/logout
    controller: App\Controller\Admin\SecurityController::logout

# register
registration:
    path: /admin23111978/register
    controller: App\Controller\Admin\SecurityController::register

forget:
    path: /admin23111978/forget
    controller: App\Controller\Admin\SecurityController::forget

dashboard:
    path: /admin23111978/dashboard
    controller: App\Controller\Admin\DashboardController::index


# propiedades-avantio
geo-propiedades-avantio:
    path:
        es: /admin23111978/propiedades-avantio/listar
        en: /{_locale}/admin23111978/avantio-properties/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-propiedades-avantio-listar:
    path:
        es: /admin23111978/propiedades-avantio/listar
        en: /{_locale}/admin23111978/avantio-properties/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-propiedades-avantio-editar:
    path:
        es: /admin23111978/propiedades-avantio/editar/{id}
        en: /{_locale}//admin23111978/avantioproperties/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-propiedades-avantio-new:
    path:
        es: /admin23111978/propiedades-avantio/new/{id}
        en: /{_locale}/admin23111978/avantio-properties/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-propiedades-avantio-pause:
    path:
        es: /admin23111978/propiedades-avantio/pause/{id}
        en: /{_locale}/admin23111978/avantio-properties/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-propiedades-avantio-play:
    path:
        es: /admin23111978/propiedades-avantio/play/{id}
        en: /{_locale}/admin23111978/avantio-properties/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma


geo-propiedades-avantio-remove:
    path:
        es: /admin23111978/propiedades-avantio/borrar/{id}
        en: /{_locale}//admin23111978/avantio-properties/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma

# pais
geo-pais:
    path:
        es: /admin23111978/pais/listar
        en: /{_locale}/admin23111978/country/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-pais-listar:
    path:
        es: /admin23111978/pais/listar
        en: /{_locale}/admin23111978/country/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-pais-editar:
    path:
        es: /admin23111978/pais/editar/{id}
        en: /{_locale}/admin23111978/country/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-pais-new:
    path:
        es: /admin23111978/pais/nuevo/{id}
        en: /{_locale}/admin23111978/country/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-pais-pause:
    path:
        es: /admin23111978/pais/pause/{id}
        en: /{_locale}/admin23111978/country/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-pais-play:
    path:
        es: /admin23111978/region/play/{id}
        en: /{_locale}/admin23111978/region/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-pais-remove:
    path:
        es: /admin23111978/pais/borrar/{id}
        en: /{_locale}/admin23111978/country/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# region
geo-region:
    path:
        es: /admin23111978/region/listar
        en: /{_locale}/admin23111978/region/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-region-listar:
    path:
        es: /admin23111978/region/listar
        en: /{_locale}/admin23111978/region/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-region-new:
    path:
        es: /admin23111978/region/nuevo/{id}
        en: /{_locale}/admin23111978/region/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-region-editar:
    path:
        es: /admin23111978/region/editar/{id}
        en: /{_locale}/admin23111978/region/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-region-pause:
    path:
        es: /admin23111978/region/pause/{id}
        en: /{_locale}/admin23111978/region/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-region-play:
    path:
        es: /admin23111978/region/play/{id}
        en: /{_locale}/admin23111978/region/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-region-remove:
    path:
        es: /admin23111978/region/borrar/{id}
        en: /{_locale}/admin23111978/region/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# ciudad
geo-ciudad:
    path:
        es: /admin23111978/ciudad/listar
        en: /{_locale}/admin23111978/city/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-ciudad-listar:
    path:
        es: /admin23111978/ciudad/listar
        en: /{_locale}/admin23111978/city/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-ciudad-new:
    path:
        es: /admin23111978/ciudad/nuevo/{id}
        en: /{_locale}/admin23111978/city/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-ciudad-editar:
    path:
        es: /admin23111978/ciudad/editar/{id}
        en: /{_locale}/admin23111978/city/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-ciudad-pause:
    path:
        es: /admin23111978/ciudad/pause/{id}
        en: /{_locale}/admin23111978/city/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-ciudad-play:
    path:
        es: /admin23111978/ciudad/play/{id}
        en: /{_locale}/admin23111978/city/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-ciudad-remove:
    path:
        es: /admin23111978/ciudad/borrar/{id}
        en: /{_locale}/admin23111978/city/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# localidad
geo-localidad:
    path:
        es: /admin23111978/localidad/listar
        en: /{_locale}/admin23111978/locality/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-localidad-listar:
    path:
        es: /admin23111978/localidad/listar
        en: /{_locale}/admin23111978/locality/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-localidad-new:
    path:
        es: /admin23111978/localidad/nuevo/{id}
        en: /{_locale}/admin23111978/locality/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-localidad-editar:
    path:
        es: /admin23111978/localidad/editar/{id}
        en: /{_locale}/admin23111978/locality/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-localidad-pause:
    path:
        es: /admin23111978/localidad/pause/{id}
        en: /{_locale}/admin23111978/locality/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-localidad-play:
    path:
        es: /admin23111978/localidad/play/{id}
        en: /{_locale}/admin23111978/locality/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-localidad-remove:
    path:
        es: /admin23111978/localidad/borrar/{id}
        en: /{_locale}/admin23111978/locality/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# distrito
geo-distrito:
    path:
        es: /admin23111978/distrito/listar
        en: /{_locale}/admin23111978/district/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-distrito-listar:
    path:
        es: /admin23111978/distrito/listar
        en: /{_locale}/admin23111978/district/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-distrito-new:
    path:
        es: /admin23111978/distrito/nuevo/{id}
        en: /{_locale}/admin23111978/district/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-distrito-editar:
    path:
        es: /admin23111978/distrito/editar/{id}
        en: /{_locale}/admin23111978/district/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-distrito-pause:
    path:
        es: /admin23111978/distrito/pause/{id}
        en: /{_locale}/admin23111978/district/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-distrito-play:
    path:
        es: /admin23111978/distrito/play/{id}
        en: /{_locale}/admin23111978/district/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-distrito-remove:
    path:
        es: /admin23111978/distrito/borrar/{id}
        en: /{_locale}/admin23111978/district/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# taxonomy
geo-taxonomy:
    path:
        es: /admin23111978/taxonomia/listar
        en: /{_locale}/admin23111978/taxonomy/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-taxonomy-listar:
    path:
        es: /admin23111978/taxonomia/listar
        en: /{_locale}/admin23111978/taxonomy/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-taxonomy-new:
    path:
        es: /admin23111978/taxonomia/nuevo/{id}
        en: /{_locale}/admin23111978/taxonomy/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-taxonomy-editar:
    path:
        es: /admin23111978/taxonomia/editar/{id}
        en: /{_locale}/admin23111978/taxonomy/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-taxonomy-pause:
    path:
        es: /admin23111978/taxonomia/pause/{id}
        en: /{_locale}/admin23111978/taxonomy/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-taxonomy-play:
    path:
        es: /admin23111978/taxonomia/play/{id}
        en: /{_locale}/admin23111978/taxonomy/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-taxonomy-remove:
    path:
        es: /admin23111978/taxonomia/borrar/{id}
        en: /{_locale}/admin23111978/taxonomy/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# taxonomy-group
geo-taxonomy-group:
    path:
        es: /admin23111978/taxonomia-grupo/listar
        en: /{_locale}/admin23111978/taxonomy-group/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-taxonomy-group-listar:
    path:
        es: /admin23111978/taxonomia-grupo/listar
        en: /{_locale}/admin23111978/taxonomy-group/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-taxonomy-group-new:
    path:
        es: /admin23111978/taxonomia-grupo/nuevo/{id}
        en: /{_locale}/admin23111978/taxonomy-group/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-taxonomy-group-editar:
    path:
        es: /admin23111978/taxonomia-grupo/editar/{id}
        en: /{_locale}/admin23111978/taxonomy-group/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-taxonomy-group-pause:
    path:
        es: /admin23111978/taxonomia-grupo/pause/{id}
        en: /{_locale}/admin23111978/taxonomy-group/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-taxonomy-group-play:
    path:
        es: /admin23111978/taxonomia-grupo/play/{id}
        en: /{_locale}/admin23111978/taxonomy-group/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-taxonomy-group-remove:
    path:
        es: /admin23111978/taxonomia-grupo/borrar/{id}
        en: /{_locale}/admin23111978/taxonomy-group/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# paginas
geo-paginas:
    path:
        es: /admin23111978/paginas/listar
        en: /{_locale}/admin23111978/pages/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-paginas-listar:
    path:
        es: /admin23111978/paginas/listar
        en: /{_locale}/admin23111978/pages/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-paginas-new:
    path:
        es: /admin23111978/paginas/nuevo/{id}
        en: /{_locale}/admin23111978/pages/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-paginas-editar:
    path:
        es: /admin23111978/paginas/editar/{id}
        en: /{_locale}/admin23111978/pages/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-paginas-pause:
    path:
        es: /admin23111978/paginas/pause/{id}
        en: /{_locale}/admin23111978/pages/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-paginas-play:
    path:
        es: /admin23111978/paginas/play/{id}
        en: /{_locale}/admin23111978/pages/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-paginas-remove:
    path:
        es: /admin23111978/paginas/borrar/{id}
        en: /{_locale}/admin23111978/pages/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# language
geo-language:
    path:
        es: /admin23111978/idiomas/listar
        en: /{_locale}/admin23111978/languages/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-language-listar:
    path:
        es: /admin23111978/idiomas/listar
        en: /{_locale}/admin23111978/languages/list
    controller: App\Controller\Admin\PageController::segmentGeoNoIdioma

geo-language-new:
    path:
        es: /admin23111978/idiomas/nuevo/{id}
        en: /{_locale}/admin23111978/languages/new/{id}
    controller: App\Controller\Admin\PageController::newNoIdioma

geo-language-editar:
    path:
        es: /admin23111978/idiomas/editar/{id}
        en: /{_locale}/admin23111978/languages/edit/{id}
    controller: App\Controller\Admin\PageController::editarNoIdioma

geo-language-pause:
    path:
        es: /admin23111978/idiomas/pause/{id}
        en: /{_locale}/admin23111978/languages/pause/{id}
    controller: App\Controller\Admin\PageController::pauseNoIdioma

geo-language-play:
    path:
        es: /admin23111978/idiomas/play/{id}
        en: /{_locale}/admin23111978/languages/play/{id}
    controller: App\Controller\Admin\PageController::playNoIdioma

geo-language-remove:
    path:
        es: /admin23111978/idiomas/borrar/{id}
        en: /{_locale}/admin23111978/languages/remove/{id}
    controller: App\Controller\Admin\PageController::removeNoIdioma


# pais API
    #geo-api-pais:
    #path: /api/pais
    #methods: ['GET']
    #controller: App\Controller\Api\PageApiController::segmentGeoNoIdioma

    #geo-api-pais-listar:
    #path: /api/pais/listar
    #methods: ['GET']
    #controller: App\Controller\Api\PageApiController::segmentGeoNoIdioma

    #geo-api-pais-new:
    #path: /api/pais/new/{id}
    #methods: ['POST']
    #controller: App\Controller\Api\PageApiController::newNoIdioma

    #geo-api-pais-add:
    #path: /api/pais/add/{id}
    #methods: ['POST']
    #controller: App\Controller\Api\PageApiController::add

    #geo-api-pais-editar:
    #path: /api/pais/editar/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::editarNoIdioma

    #geo-api-pais-update:
    #path: /api/pais/update/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::updateNoIdioma

    #geo-api-pais-pause:
    #path: /api/pais/pause/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::pauseNoIdioma

    #geo-api-pais-play:
    #path: /api/pais/play/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::playNoIdioma

    #geo-api-pais-remove:
    #path: /api/pais/remove/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::removeNoIdioma

    #geo-api-country-idioma:
    #path: /{_locale}/api/country
    #methods: ['GET']
    #controller: App\Controller\Api\PageApiController::segmentGeoIdioma

    #geo-api-country-new-idioma:
    #path: /{_locale}/api/country/new/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::newIdioma

    #geo-api-country-listar-idioma:
    #path: /{_locale}/api/country/listar
    #methods: ['GET']
    #controller: App\Controller\Api\PageApiController::segmentGeoIdioma

    #geo-api-country-editar-idioma:
    #path: /{_locale}/api/country/editar/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::editarIdioma

    #geo-api-country-update-idioma:
    #path: /{_locale}/api/country/update/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::updateIdioma

    #geo-api-country-pause-idioma:
    #path: /{_locale}/api/country/pause/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::pauseIdioma

    #geo-api-country-play-idioma:
    #path: /{_locale}/api/country/play/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::playIdioma

    #geo-api-country-remove-idioma:
    #path: /{_locale}/api/country/remove/{id}
    #methods: ['PUT']
    #controller: App\Controller\Api\PageApiController::removeIdioma